### ISSUE TITLE
Missing line of code in focuser.py possibly other places.

### ISSUE THREAD

**Issue by jmhannon** [ASCOMInitiative/AlpycaDevice#10]
It looks like a line of code is missing in the new focuser.py class connected at line 88

           # --------------------------------
            ### CONNECT/DISCONNECT()PARAM) ###
            # --------------------------------
           resp.text = MethodResponse(req).json
        except Exception as ex:
            DriverException(0x500, 'Focuser.{Memname} failed', ex)).json

I think it should be:
       # --------------------------------
            ### CONNECT/DISCONNECT()PARAM) ###
            # --------------------------------
           resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(None, req,
            DriverException(0x500, 'Focuser.{Memname} failed', ex)).json
Also there is an extra right parentheses at the end of line 79.

**Comment by BobDenny** [comment]
New templates generated from YAML. Class Connected corrected in several ways, including the missing line. But `MethodResponse(*)` does not need `None` as a first parameter. Also the error message contained `{Memname} ` which is not correct in that context and therefore not substituted when generating the templares. It should say  "*devname*.Connected"
