### ISSUE TITLE
Thanks for creating this

### ISSUE THREAD

**Issue by IanCassTwo** [ASCOMInitiative/AlpycaDevice#4]
Bob, thanks for releasing this. I've used it to make a Raspberry Pi Camera driver which you can find here. https://github.com/IanCassTwo/rpicam-ascom-alpaca. 

On the whole, it was quite easy to do but there was a few oddities and things that I struggled with.

1) The camera template has some duplicate on_put methods with the same signature in some classes. I couldn't see why they were there so I deleted them

2) Some property responses want more fields other than just "Value" so I ended up subclassing the Property Response class under a new name to suit. Not sure if there's a better way to do it

3) The biggest thing I struggled with was getting the ImageArray in the correct format. I got there eventually but documentation regarding this is terrible on the ASCOM site.

**Comment by BobDenny** [comment]
Thanks for the info. The templates were generated from YAML so it's not surprising that you, being the first to implement a Camera, found some issues. I'll look at providing the additional hooks you pointed out, probably after a few more issues pile up. You have a running driver so ......

I want to make sure you implemented the ImageBytes format.  If not then you really should. The documentation is part of the [Alpaca API Reference](https://github.com/ASCOMInitiative/ASCOMRemote/raw/main/Documentation/ASCOM%20Alpaca%20API%20Reference.pdf)

**Comment by IanCassTwo** [comment]
Yes, I implemented the ImageBytes format and it's very quick. I also used orjson instead of the built-in json and it's 3x faster at serializing.

**Comment by BobDenny** [comment]
Excellent. I'm closing this ticket now.
