### ISSUE TITLE
ObservingConditions Template Exception

### ISSUE THREAD

**Issue by CBaker007** [ASCOMInitiative/AlpycaDevice#6]
When trying to use the observingconditions.py template as described in the documentation, when I try to run the code, I get the following error:
![2023-07-28_22-04-18](https://github.com/ASCOMInitiative/AlpycaDevice/assets/77406892/8b04e591-ded4-43ca-8c8a-df074857bb41)

I am not a well versed programmer and brand new to Python, but I dropped "to_int" (and later "to_float" when that produced a similar error) and that seems to work.  I am not sure if it can't find those to import, does not need them, or were not defined for some reason.

**Comment by BobDenny** [comment]
These are template errors.  You are correct to remove them.  I am making fixes to the template generator. The fixes will be in 0.4. Thank you.

**Comment by BobDenny** [comment]
Released 0.4 with this fixed in the templates.
