### ISSUE TITLE
Log files created are named "rotatorXXX.log" even when other device

### ISSUE THREAD

**Issue by CBaker007** [ASCOMInitiative/AlpycaDevice#7]
When using the code as described in the documentation to create a different device, for example ObservingConditions, the log file that is generated is "rotatorXXX.log" instead of say "observingconditionsXXX.log".  In the log.py file, line 74 appears to have the name of the log file hard coded to "rotator.log".  Might want to add this to your changes in the documentation to modify this line in log.py or add it as a config.toml setting.

![2023-07-28_22-27-04](https://github.com/ASCOMInitiative/AlpycaDevice/assets/77406892/2d8e5a39-4091-4718-86bc-142140586b84)

**Comment by BobDenny** [comment]
This is a good one. Thank you!!! Since the server can host multiple device types and the logging is part of the server I'll change the file to `alpyca`. Change committed for 0.4
